"""
app_new.py

Main entry point for the DX Usage Intelligence Dashboard.

This page presents an executive overview of the IUDX platform,
displaying key performance indicators (KPIs), platform health,
recent changes, and navigation to the dashboard modules.

The dashboard reads the latest snapshot generated by the
automated data pipeline and presents a high-level summary
for stakeholders.
"""

import streamlit as st
from datetime import datetime

from utils import load_latest_snapshot, load_snapshot_history
from delta_detector import get_latest_changes
from theme import apply_theme
from dashboard_components import (
    hero,
    metric_card,
    section,
    info_card,
    status_card,
    footer,
)

# -------------------------------------------------------------------
# Application Setup
# -------------------------------------------------------------------

st.set_page_config(
    page_title="DX Usage Intelligence Dashboard",
    page_icon="📊",
    layout="wide",
)

apply_theme()

data = load_latest_snapshot()

if not data:
    st.error("No snapshot data available.")
    st.stop()

history = load_snapshot_history()
changes = get_latest_changes()

ts = datetime.fromisoformat(data["timestamp"])
formatted = ts.strftime("%d %b %Y, %I:%M %p UTC")

# -------------------------------------------------------------------
# Dashboard Header
# -------------------------------------------------------------------

hero(
    "DX Usage Intelligence Dashboard",
    "Executive overview of the IUDX Data Exchange platform",
)

st.caption(f"Last Updated: {formatted}")
st.markdown("<div style='height:12px'></div>", unsafe_allow_html=True)

# -------------------------------------------------------------------
# Executive Summary
#
# metric_card's signature is metric_card(title, value, icon, ...).
# Arguments are passed in the order the function actually expects
# (title, then value, then icon) so the component behaves correctly
# no matter how the styling changes later.
# -------------------------------------------------------------------

col1, col2, col3, col4 = st.columns(4)

with col1:
    metric_card("Datasets", f"{data['total_datasets']:,}", "📂")

with col2:
    metric_card("Users", f"{data['user_count']:,}", "👥")

with col3:
    metric_card("Providers", data["total_providers"], "🏢")

with col4:
    metric_card("Domains", data["total_domains"], "🌍")

# -------------------------------------------------------------------
# Platform Health
# -------------------------------------------------------------------

section("Platform Health")

health_col, summary_col = st.columns(2)

with health_col:
    status_card(True)

with summary_col:
    info_card(
        "Snapshot Summary",
        (
            f"<b>Snapshots:</b> {len(history)}"
            f"<br><b>Last Updated:</b> {formatted}"
        ),
    )

# -------------------------------------------------------------------
# Prepare Summary Statistics
# -------------------------------------------------------------------

domains = sorted(
    data["domains"],
    key=lambda x: x["count"],
    reverse=True,
)

providers = sorted(
    data["providers"],
    key=lambda x: x["count"],
    reverse=True,
)

largest_domain = (
    domains[0]
    if domains
    else {"name": "N/A", "count": 0}
)

largest_provider = (
    providers[0]
    if providers
    else {"name": "N/A", "count": 0}
)

open_count = next(
    (
        item["count"]
        for item in data.get("access_policies", [])
        if item["name"] == "open"
    ),
    0,
)

open_pct = (
    (open_count / data["total_datasets"]) * 100
    if data["total_datasets"]
    else 0
)

# -------------------------------------------------------------------
# Key Insights
# -------------------------------------------------------------------

section("Key Insights")

platform_col, changes_col = st.columns(2)

with platform_col:
    info_card(
        "Platform",
        (
            f"Largest Domain: <b>{largest_domain['name']}</b><br>"
            f"Largest Provider: <b>{largest_provider['name']}</b><br>"
            f"Open Datasets: <b>{open_pct:.1f}%</b>"
        ),
    )

with changes_col:
    if changes:
        info_card(
            "Recent Changes",
            (
                f"Dataset Growth: <b>{changes['dataset_growth']:+}</b><br>"
                f"New Users: <b>{changes['new_user_count']:+}</b><br>"
                f"New Providers: <b>{len(changes['new_providers'])}</b><br>"
                f"New Domains: <b>{len(changes['new_domains'])}</b>"
            ),
        )
    else:
        info_card(
            "Recent Changes",
            "Not enough snapshots for comparison.",
        )

# -------------------------------------------------------------------
# Dashboard Modules
# -------------------------------------------------------------------

section("Dashboard Modules")

module1, module2, module3 = st.columns(3)

with module1:
    info_card(
        "📊 Dataset Analysis",
        "Dataset distributions and metadata",
    )

with module2:
    info_card(
        "📈 Trends",
        "Historical growth",
    )

with module3:
    info_card(
        "🤖 AI Assistant",
        "Natural language dashboard queries",
    )

# -------------------------------------------------------------------
# Footer
# -------------------------------------------------------------------

footer()
